# fly.toml file generated for toe2 on 2023-01-10T11:50:21-05:00

app = "toe2"
kill_signal = "SIGTERM"

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'bidtactoe.com'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
